In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/workspaces/vikrant_dubai/final/comb/AJ_combined.csv')

/tmp/ipykernel_6468/1861894904.py:1: DtypeWarning: Columns (6,9,15,23,27,29,39,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/workspaces/vikrant_dubai/final/comb/AJ_combined.csv')

In [6]:
df

,Station Name,Date,Time,SO2,Data Cap. (SO2),SO2 Avg,NO2,Data Cap. (NO2),NO2 Avg,O3,...,O-Xylene,Ethylbenzene,MP-Xylene,Benzene,CH4,NMHC,THC,Noise,Solar Radiation,Atm P.
0,Jurf,01/01/2023,00:00:00,8.122,NaN,NaN,74.824,NaN,NaN,1.9632,...,NaN,NaN,NaN,NaN,2.577,1.311,3.888,80.86,NaN,NaN
1,Jurf,01/01/2023,01:00:00,6.026,NaN,NaN,77.268,NaN,NaN,3.9264,...,NaN,NaN,NaN,NaN,2.937,1.539,4.476,81.48,NaN,NaN
2,Jurf,01/01/2023,02:00:00,4.454,NaN,NaN,68.432,NaN,NaN,3.9264,...,NaN,NaN,NaN,NaN,3.358,1.379,4.737,81.68,NaN,NaN
3,Jurf,01/01/2023,03:00:00,9.170000000000002,NaN,NaN,68.996,NaN,NaN,3.9264,...,NaN,NaN,NaN,NaN,3.144,1.343,4.487,81.69,NaN,NaN
4,Jurf,01/01/2023,04:00:00,7.598,NaN,NaN,71.252,NaN,NaN,3.9264,...,NaN,NaN,NaN,NaN,2.923,1.32,4.242,81.74,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43817,AjmanX,31/12/2023,19:00:00,2.75,NaN,NaN,14.44,NaN,NaN,43.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1015.3,55.69,0.0
43818,AjmanX,31/12/2023,20:00:00,2.67,NaN,NaN,11.8,NaN,NaN,38.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1015.1,55.56,0.0
43819,AjmanX,31/12/2023,21:00:00,2.6,NaN,NaN,10.48,NaN,NaN,33.51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1015.0,54.56,0.0
43820,AjmanX,31/12/2023,22:00:00,2.64,NaN,NaN,14.42,NaN,NaN,24.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1014.9,53.10,0.0
43821,AjmanX,31/12/2023,23:00:00,2.77,NaN,NaN,27.58,NaN,NaN,8.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1014.9,51.30,0.0

In [5]:
df.columns

Index(['Station Name', 'Date', 'Time', 'SO2', 'Data Cap. (SO2)', 'SO2 Avg',
       'NO2', 'Data Cap. (NO2)', 'NO2 Avg', 'O3', 'Data Cap. (O3)',
       'O3 8H Avg.', 'Daily Capture O3', 'O3 Daily Average',
       'O3 Daily Average (NS)', 'CO', 'Data Cap. (CO)', 'CO 8H Avg.',
       'Daily Capture CO', 'CO Daily Average', 'PM10', 'Data Cap. (PM10)',
       'PM10 Avg', 'PM2.5', 'Data Cap. (PM2.5)', 'PM2.5 Avg',
       'Lower Ambient Temperature', 'Upper Ambient Temperature',
       'Barometric Pressure', 'Relative Humidity', 'Wind Direction',
       'Wind Speed', 'H2S', 'Toluene', 'O-Xylene', 'Ethylbenzene', 'MP-Xylene',
       'Benzene', 'CH4', 'NMHC', 'THC', 'Noise', 'Solar Radiation', 'Atm P.'],
      dtype='object')